spring:
  application:
    name: user-service
  
  config:
    import: optional:configserver:http://config-server:8888
  
  cloud:
    config:
      username: admin
      password: admin
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

# Configuration Eureka de base (sera complétée par le config-server)
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://admin:admin123@discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: user-service

# Configuration du serveur
server:
  port: 8084

# Configuration de base pour les endpoints de management
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,eureka
  endpoint:
    health:
      show-details: always

